"""init

Revision ID: 4f6c01cbef46
Revises: 
Create Date: 2026-05-16 20:45:57.736870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f6c01cbef46'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('escalation_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('trigger_event', sa.Enum('goal_not_submitted', 'goal_not_approved', 'checkin_not_done', name='trigger_event_enum'), nullable=False),
    sa.Column('days_threshold', sa.Integer(), nullable=False),
    sa.Column('notify_employee', sa.Boolean(), nullable=True),
    sa.Column('notify_manager', sa.Boolean(), nullable=True),
    sa.Column('notify_hr', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('employee', 'manager', 'admin', name='user_role'), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cycles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('goal_setting_open', sa.Date(), nullable=False),
    sa.Column('q1_open', sa.Date(), nullable=False),
    sa.Column('q2_open', sa.Date(), nullable=False),
    sa.Column('q3_open', sa.Date(), nullable=False),
    sa.Column('q4_open', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_sheets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'approved', 'returned', name='sheet_status'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('total_weightage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'cycle_id', name='uq_employee_cycle')
    )
    op.create_table('checkin_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_sheet_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.Enum('q1', 'q2', 'q3', 'q4', 'annual', name='quarter_enum'), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_sheet_id'], ['goal_sheets.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_sheet_id', sa.UUID(), nullable=False),
    sa.Column('thrust_area', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uom_type', sa.Enum('min', 'max', 'timeline', 'zero', name='uom_type'), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('weightage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('parent_goal_id', sa.UUID(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['goal_sheet_id'], ['goal_sheets.id'], ),
    sa.ForeignKeyConstraint(['parent_goal_id'], ['goals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('goal_achievements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('quarter', sa.Enum('q1', 'q2', 'q3', 'q4', 'annual', name='quarter_enum'), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('completion_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('not_started', 'on_track', 'completed', name='achievement_status'), nullable=True),
    sa.Column('computed_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_id'], ['cycles.id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal_id', 'quarter', name='uq_goal_quarter')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal_achievements')
    op.drop_table('goals')
    op.drop_table('checkin_comments')
    op.drop_table('goal_sheets')
    op.drop_table('cycles')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('escalation_rules')
    op.drop_table('departments')
    # ### end Alembic commands ###
