"""add outbox table

Revision ID: b8cbad85aab9
Revises: 4f6c01cbef46
Create Date: 2026-05-17 14:17:34.034570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8cbad85aab9'
down_revision: Union[str, None] = '4f6c01cbef46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_status_created', 'outbox_events', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index('idx_achieve_goal_quarter', 'goal_achievements', ['goal_id', 'quarter'], unique=False)
    op.create_index('idx_sheet_cycle_emp', 'goal_sheets', ['cycle_id', 'employee_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sheet_cycle_emp', table_name='goal_sheets')
    op.drop_index('idx_achieve_goal_quarter', table_name='goal_achievements')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index('idx_outbox_status_created', table_name='outbox_events')
    op.drop_table('outbox_events')
    # ### end Alembic commands ###
